name: Trigger GitLab Pipeline

on:
  push:
    branches:
      - main   # ✅ Run this workflow only when code is pushed to main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab pipeline via token
        run: |
          curl -X POST \
            -F token=${{ secrets.GITLAB_TOKEN }} \
            -F ref=main \
            https://gitlab.com/api/v4/projects/71447214/trigger/pipeline
